plugins {
    id 'com.android.application'
}

android {
    namespace 'game.dont100.test'
    compileSdk 36

    defaultConfig {
        applicationId 'game.dont100.polishedtest'
        minSdk 24
        targetSdk 36
        versionCode 3
        versionName '4.2.0-rc.1.2-polish'
    }

    buildTypes {
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
