import { matchPrograms, inferProjectTypes } from './engine.mjs';
import {loadWorkspace,saveWorkspace,saveProfile,upsertProject,saveScan,latestScan,setWatch,isWatched,unreadAlerts,markAlertsRead,addWatchAlerts,exportWorkspace} from './workspace.mjs';

const $=s=>document.querySelector(s);
const labels={confirmed:'Éligibilité confirmée sur les critères saisis',probable:'Probablement éligible',to_verify:'À vérifier',not_eligible:'Non éligible'};
const availabilityLabels={open:'Ouvert',upcoming:'Bientôt',call_based:'Selon appel',closed:'Appel clôturé',check:'Disponibilité à vérifier'};
const ENGINE_VERSION='m2.1-local-1';
let programs=[],catalog={version:'2026-10-01.2'},state=loadWorkspace(),activeProjectId=null,lastResults=[];

async function boot(){
  const [base,extra]=await Promise.all([
    fetch('./data/programs.json').then(r=>r.json()),
    fetch('./data/programs_2026q4.json').then(r=>r.json()).catch(()=>[])
  ]);
  programs=[...base,...extra];
  try{catalog=await (await fetch('./data/catalog.meta.json')).json();}catch{}
  $('#verifiedCount').textContent=programs.length;$('#catalogVersion').textContent=`Catalogue ${catalog.version||''}`;
  hydrateProfile();renderWorkspace();bind();runWatchedProjects();
}
function bind(){
  $('#run').addEventListener('click',()=>run(true));$('#saveProject').addEventListener('click',saveCurrentProject);$('#example').addEventListener('click',fillExample);
  $('#toggleWatch').addEventListener('click',toggleWatch);$('#openWorkspace').addEventListener('click',goWorkspace);$('#heroWorkspace').addEventListener('click',goWorkspace);
  $('#markRead').addEventListener('click',()=>{markAlertsRead(state);persist();renderWorkspace();});$('#exportData').addEventListener('click',downloadExport);
}
function goWorkspace(){renderWorkspace();$('#workspace').scrollIntoView({behavior:'smooth'});}
function val(id){return $(id)?.value??''} function tri(id){const v=val(id);return v==='yes'?true:v==='no'?false:null} function setTri(id,v){$(id).value=v===true?'yes':v===false?'no':'unknown'}
function profileFromForm(){return {company_name:val('#companyName').trim(),canton:val('#canton'),fte:Number(val('#fte')||0),industry_hightech:tri('#industry'),rd_or_production_in_canton:tri('#localRD'),industrial_company:tri('#industrial'),production_tool_in_canton:tri('#productionTool'),is_startup:tri('#startup'),market_established:tri('#market'),local_jobs_impact:tri('#jobsImpact'),swiss_uid:val('#swissUid').trim()};}
function projectFromForm(){return {id:activeProjectId||undefined,name:val('#projectName').trim()||'Projet sans nom',description:val('#description').trim(),budget_chf:Number(val('#budget')||0)||null,target_start_date:val('#startDate')||null,project_started:tri('#started'),swiss_research_partner:tri('#researchPartner'),geneva_research_partner:tri('#genevaPartner'),foreign_local_partner:tri('#foreignPartner')};}
function matchInput(){const c=profileFromForm(),p=projectFromForm();return {canton:c.canton,fte:c.fte,description:p.description,industry_hightech:c.industry_hightech,rd_or_production_in_canton:c.rd_or_production_in_canton,industrial_company:c.industrial_company,production_tool_in_canton:c.production_tool_in_canton,is_startup:c.is_startup,market_established:c.market_established,project_started:p.project_started,swiss_research_partner:p.swiss_research_partner,geneva_research_partner:p.geneva_research_partner,foreign_local_partner:p.foreign_local_partner,local_jobs_impact:c.local_jobs_impact,swiss_uid:c.swiss_uid,as_of_date:new Date().toISOString().slice(0,10),project_types:inferProjectTypes(p.description)};}
function hydrateProfile(){const p=state.profile||{};if(p.company_name)$('#companyName').value=p.company_name;if(p.canton)$('#canton').value=p.canton;if(p.fte!=null)$('#fte').value=p.fte;setTri('#industry',p.industry_hightech);setTri('#localRD',p.rd_or_production_in_canton);setTri('#industrial',p.industrial_company);setTri('#productionTool',p.production_tool_in_canton);setTri('#startup',p.is_startup);setTri('#market',p.market_established);setTri('#jobsImpact',p.local_jobs_impact);if(p.swiss_uid)$('#swissUid').value=p.swiss_uid;}
function hydrateProject(p){activeProjectId=p.id;$('#projectName').value=p.name||'';$('#description').value=p.description||'';$('#budget').value=p.budget_chf||'';$('#startDate').value=p.target_start_date||'';setTri('#started',p.project_started);setTri('#researchPartner',p.swiss_research_partner);setTri('#genevaPartner',p.geneva_research_partner);setTri('#foreignPartner',p.foreign_local_partner);updateWatchBar();$('#diagnostic').scrollIntoView({behavior:'smooth'});}
function persist(){saveWorkspace(state);updateAlertCount();}
function saveCurrentProject(show=true){saveProfile(state,profileFromForm());const project=upsertProject(state,projectFromForm());activeProjectId=project.id;persist();renderWorkspace();updateWatchBar();if(show)notice('Projet enregistré dans ce navigateur.');return project;}
function run(save=true){const input=matchInput();if(!input.description.trim()){$('#results').innerHTML='<div class="empty">Décrivez votre projet pour lancer l’analyse.</div>';return [];}const results=matchPrograms(programs,input);lastResults=results;const good=results.filter(x=>x.eligibility!=='not_eligible'&&x.relevance>=40);$('#summary').hidden=false;$('#summary').innerHTML=`<strong>${good.length}</strong> pistes à examiner sur <strong>${programs.length}</strong> dispositifs vérifiés. <span>Thèmes: ${input.project_types.join(', ')||'aucun détecté'}.</span>`;$('#results').innerHTML=results.filter(x=>x.relevance>=38||x.eligibility==='not_eligible').map(card).join('');if(save){const project=saveCurrentProject(false);const previous=latestScan(state,project.id);if(isWatched(state,project.id)&&previous)addWatchAlerts(state,project.id,previous.result_snapshot,results,catalog.version);saveScan(state,{project_id:project.id,input,results,catalog_version:catalog.version,engine_version:ENGINE_VERSION});persist();renderWorkspace();updateWatchBar();}return results;}
function money(f){if(!f)return 'Selon dossier';const a=[];if(f.amount_min_chf)a.push(`dès CHF ${f.amount_min_chf.toLocaleString('fr-CH')}`);if(f.amount_max_chf)a.push(`jusqu’à CHF ${f.amount_max_chf.toLocaleString('fr-CH')}`);if(f.amount_max_eur)a.push(`jusqu’à EUR ${f.amount_max_eur.toLocaleString('fr-CH')}`);if(f.rate_max)a.push(`${Math.round(f.rate_max*100)}% max.`);return a.join(' • ')||f.note||'Selon dossier';}
function list(items,klass=''){return items?.length?`<ul class="${klass}">${items.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:''}
function card(x){const p=x.program;const av=x.availability||{code:'check',label:'Disponibilité à vérifier'};return `<article class="result ${x.eligibility}"><div class="score"><b>${x.relevance}</b><span>match</span></div><div class="resultMain"><div class="row"><div><div class="authority">${escapeHtml(p.authority)}</div><h3>${escapeHtml(p.name)}</h3></div><div class="badges"><span class="availability availability-${av.code}">${escapeHtml(availabilityLabels[av.code]||av.label)}</span><span class="badge">${labels[x.eligibility]}</span></div></div><div class="amount">${money(p.funding)}</div>${x.blockers.length?`<details open><summary>Pourquoi exclu</summary>${list(x.blockers,'bad')}</details>`:''}${x.reasons.length?`<details><summary>Pourquoi cette piste apparaît</summary>${list(x.reasons,'good')}</details>`:''}${x.checks.length?`<details><summary>À confirmer</summary>${list(x.checks,'warn')}</details>`:''}<details><summary>Conditions et documents</summary>${list(p.hard_requirements)}${list(p.documents)}</details><div class="foot"><span>Vérifié le ${p.verified_on} • ${escapeHtml(av.label||availabilityLabels[av.code]||'')}</span><a href="${p.source}" target="_blank" rel="noopener">Source officielle ↗</a></div></div></article>`}
function toggleWatch(){if(!activeProjectId)saveCurrentProject(false);const enabled=!isWatched(state,activeProjectId);setWatch(state,activeProjectId,enabled);persist();updateWatchBar();renderWorkspace();notice(enabled?'GrantWatch activé pour ce projet.':'GrantWatch désactivé.');}
function updateWatchBar(){if(!activeProjectId){$('#watchBar').hidden=true;return}$('#watchBar').hidden=false;const on=isWatched(state,activeProjectId);$('#toggleWatch').textContent=on?'Désactiver la surveillance':'Surveiller ce projet';$('#toggleWatch').classList.toggle('watchOn',on);}
function runWatchedProjects(){for(const w of state.watches.filter(x=>x.enabled)){const p=state.projects.find(x=>x.id===w.project_id);const previous=latestScan(state,w.project_id);if(!p||!previous||previous.catalog_version===catalog.version)continue;const input={...previous.input,as_of_date:new Date().toISOString().slice(0,10)};const current=matchPrograms(programs,input);addWatchAlerts(state,p.id,previous.result_snapshot,current,catalog.version);saveScan(state,{project_id:p.id,input,results:current,catalog_version:catalog.version,engine_version:ENGINE_VERSION});}persist();renderWorkspace();}
function renderWorkspace(){updateAlertCount();const projects=state.projects||[];$('#projectList').innerHTML=projects.length?projects.map(p=>{const watched=isWatched(state,p.id);const scans=state.scans.filter(s=>s.project_id===p.id);return `<button class="projectCard" data-project="${p.id}"><b>${escapeHtml(p.name)}</b><span>${escapeHtml((p.description||'').slice(0,100))}${(p.description||'').length>100?'…':''}</span><small>${watched?'● GrantWatch actif':'○ Non surveillé'} • ${scans.length} analyse(s)</small></button>`}).join(''):'<div class="empty smallEmpty">Aucun projet enregistré.</div>';document.querySelectorAll('[data-project]').forEach(el=>el.addEventListener('click',()=>hydrateProject(projects.find(p=>p.id===el.dataset.project))));const alerts=state.alerts||[];$('#alertList').innerHTML=alerts.length?alerts.slice(0,12).map(a=>`<div class="alertItem ${a.read_at?'read':''}"><b>${escapeHtml(a.title)}</b><span>${escapeHtml(a.body)}</span><small>${formatDate(a.created_at)}</small></div>`).join(''):'<div class="empty smallEmpty">Aucune alerte.</div>';$('#scanList').innerHTML=state.scans.length?state.scans.slice(0,15).map(s=>{const p=projects.find(x=>x.id===s.project_id);const viable=s.result_snapshot.filter(x=>x.eligibility!=='not_eligible'&&x.relevance>=40).length;return `<div class="scanItem"><b>${escapeHtml(p?.name||'Projet')}</b><span>${viable} piste(s) • catalogue ${escapeHtml(s.catalog_version||'—')}</span><small>${formatDate(s.created_at)}</small></div>`}).join(''):'<div class="empty smallEmpty">Aucune analyse sauvegardée.</div>';}
function updateAlertCount(){const n=unreadAlerts(state).length;$('#alertCount').textContent=n;$('#alertCount').hidden=!n;}
function downloadExport(){const blob=new Blob([exportWorkspace(state)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`subvench-export-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function notice(text){$('#saveNotice').hidden=false;$('#saveNotice').textContent=text;setTimeout(()=>$('#saveNotice').hidden=true,2600)}
function formatDate(x){try{return new Intl.DateTimeFormat('fr-CH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x))}catch{return x}}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function fillExample(){$('#companyName').value='AlpTech SA';$('#canton').value='VD';$('#fte').value='38';$('#projectName').value='Automatisation ligne 2027';$('#budget').value='240000';$('#industry').value='yes';$('#localRD').value='yes';$('#industrial').value='yes';$('#productionTool').value='yes';$('#startup').value='no';$('#market').value='yes';$('#started').value='no';$('#researchPartner').value='unknown';$('#genevaPartner').value='unknown';$('#foreignPartner').value='unknown';$('#jobsImpact').value='yes';$('#description').value="Nous sommes une PME industrielle vaudoise. Nous voulons automatiser une ligne de production et développer un prototype de nouveau produit. Budget prévu CHF 240'000 avec un bureau d'ingénierie externe. Le projet n'a pas encore commencé.";run(true);}
boot();