export function normalize(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
export function inferProjectTypes(description=''){const t=normalize(description);const maps={innovation:['innovation','prototype','proof of concept','poc','r&d','recherche','nouveau produit','technologie'],product:['produit','prototype','homologation','certification'],production:['production','machine','equipement','procédé','process','moule','automatisation','industrialisation'],certification:['certification','homologation','ce','fda','iso'],export:['export','international','etranger','nouveau marche','distributeur'],market:['marche','client','commercial','distributeur'],tradefair:['salon','foire','exposition','convention','congres','stand'],training:['formation','former','competence','employe'],ip:['brevet','propriete intellectuelle','patent','pct'],investment:['investissement','acheter une machine','acquisition','infrastructure','credit','banque','financement','pret'],energy:['energie','energetique','electricite','co2','climat','cleantech','efficience'],digitalisation:['digitalisation','numerique','digital','logiciel','automatisation'],startup:['startup','start-up'],scaleup:['scale-up','scaleup','croissance','disruptif'],impact:['impact','social','environnemental','durable'],financing:['financement','pret','credit','cautionnement','tresorerie']};return Object.entries(maps).filter(([,words])=>words.some(w=>t.includes(normalize(w)))).map(([k])=>k);}
function cantonMatches(program,canton){return program.cantons.includes('ALL')||program.cantons.includes(canton);}
export function availabilityOf(program,asOf=new Date().toISOString().slice(0,10)){
  const s=String(program.status||'').toLowerCase();
  if(s==='open')return{code:'open',label:'Ouvert'};
  if(s.startsWith('open_from_')){const d=s.replace('open_from_','');return asOf>=d?{code:'open',label:'Ouvert'}:{code:'upcoming',label:`Ouverture ${d}`};}
  if(s.startsWith('closed'))return{code:'closed',label:'Appel clôturé'};
  if(s.includes('seasonal')||s.includes('call_based')||s.includes('open_or_call'))return{code:'call_based',label:'Selon appel'};
  return{code:'check',label:'Disponibilité à vérifier'};
}
export function evaluate(program,profile){const reasons=[],blockers=[],checks=[];const text=normalize(profile.description||'');const types=profile.project_types?.length?profile.project_types:inferProjectTypes(profile.description);const cp=program.company_profile||{};const availability=availabilityOf(program,profile.as_of_date);
if(!cantonMatches(program,profile.canton))blockers.push(`Programme non disponible pour le canton ${profile.canton}.`);else reasons.push(`Périmètre géographique compatible (${profile.canton}).`);
if(cp.max_fte!=null&&Number(profile.fte)>cp.max_fte)blockers.push(`Taille supérieure à ${cp.max_fte} ETP.`);if(cp.max_fte!=null&&Number(profile.fte)<=cp.max_fte)reasons.push(`Taille compatible (≤ ${cp.max_fte} ETP).`);
if(cp.requires_industry_or_hightech){if(profile.industry_hightech===true)reasons.push('Profil industrie / technologies de pointe déclaré.');else if(profile.industry_hightech===false)blockers.push('Programme réservé aux entreprises de l’industrie / technologies de pointe.');else checks.push('Confirmer que l’entreprise relève de l’industrie ou des technologies de pointe.');}
if(cp.requires_rd_or_production_in_canton){if(profile.rd_or_production_in_canton===true)reasons.push('R&D ou production dans le canton confirmée.');else if(profile.rd_or_production_in_canton===false)blockers.push('R&D ou production dans le canton requise.');else checks.push('Confirmer une activité de R&D ou production dans le canton.');}
if(cp.requires_industrial_company){if(profile.industrial_company===true)reasons.push('Entreprise industrielle déclarée.');else if(profile.industrial_company===false)blockers.push('Mesure réservée aux entreprises industrielles.');else checks.push('Confirmer le caractère industriel de l’entreprise.');}
if(cp.requires_production_tool_in_canton){if(profile.production_tool_in_canton===true)reasons.push('Outil de production local confirmé.');else if(profile.production_tool_in_canton===false)blockers.push('Outil de production dans le canton requis.');else checks.push('Confirmer la présence d’un outil de production dans le canton.');}
if(cp.requires_startup){if(profile.is_startup===true)reasons.push('Profil start-up déclaré.');else if(profile.is_startup===false)blockers.push('Programme destiné aux start-up répondant aux critères du dispositif.');else checks.push('Confirmer le statut de start-up selon les critères du dispositif.');}
if(cp.requires_market_established){if(profile.market_established===true)reasons.push('Entreprise déjà établie sur le marché.');else if(profile.market_established===false)blockers.push('Le dispositif exige une entreprise déjà établie sur le marché.');else checks.push('Confirmer que l’entreprise est déjà établie sur le marché.');}
if(cp.requires_project_not_started){if(profile.project_started===false)reasons.push('Projet déclaré non commencé.');else if(profile.project_started===true)blockers.push('La demande doit être déposée avant le début du projet.');else checks.push('Confirmer que le projet n’a pas encore commencé.');}
if(cp.requires_swiss_research_partner){if(profile.swiss_research_partner===true)reasons.push('Partenaire de recherche suisse identifié.');else if(profile.swiss_research_partner===false)blockers.push('Un partenaire de recherche suisse est requis.');else checks.push('Confirmer l’existence d’un partenaire de recherche suisse.');}
if(cp.requires_geneva_research_partner){if(profile.geneva_research_partner===true)reasons.push('Partenaire UNIGE/HES-SO Genève identifié.');else if(profile.geneva_research_partner===false)blockers.push('Une collaboration avec UNIGE ou HES-SO Genève est requise.');else checks.push('Confirmer une collaboration avec UNIGE ou HES-SO Genève.');}
if(cp.requires_foreign_local_partner){if(profile.foreign_local_partner===true)reasons.push('Partenaire/sous-traitant local dans le pays cible identifié.');else if(profile.foreign_local_partner===false)blockers.push('Un sous-traitant indépendant dans le pays cible est requis.');else checks.push('Confirmer un sous-traitant indépendant dans le pays cible.');}
if(cp.requires_local_jobs_impact){if(profile.local_jobs_impact===true)reasons.push('Impact emploi local déclaré.');else if(profile.local_jobs_impact===false)blockers.push('Un impact sur la création ou le maintien d’emplois local est requis.');else checks.push('Confirmer l’impact sur la création ou le maintien d’emplois local.');}
if(cp.requires_swiss_uid)checks.push('Confirmer un siège en Suisse et un numéro IDE/UID suisse.');if(cp.requires_swiss_value_creation)checks.push('Confirmer la création de valeur en Suisse.');
for(const check of program.manual_checks||[])checks.push(check);
if(availability.code==='closed')checks.push('L’appel identifié est clôturé: vérifier la prochaine fenêtre de candidature.');if(availability.code==='upcoming')checks.push(`Le dispositif n’est pas encore ouvert à la date analysée (${availability.label}).`);if(availability.code==='call_based')checks.push('Vérifier qu’un appel à projets est actuellement ouvert et sa date limite.');
const typeHits=program.project_types.filter(t=>types.includes(t)).length;const kwHits=program.keywords.filter(k=>text.includes(normalize(k))).length;if(typeHits)reasons.push(`${typeHits} thème(s) projet correspondant(s).`);if(kwHits)reasons.push(`${kwHits} indice(s) textuel(s) correspondant(s).`);let relevance=28+Math.min(36,typeHits*12)+Math.min(28,kwHits*7);if(cantonMatches(program,profile.canton))relevance+=8;relevance=Math.max(0,Math.min(98,relevance));let eligibility='to_verify';if(blockers.length)eligibility='not_eligible';else if(checks.length===0&&(typeHits+kwHits)>0)eligibility='confirmed';else if((typeHits+kwHits)>0)eligibility='probable';return{program,eligibility,relevance,reasons,blockers,checks,inferred_types:types,availability};}
export function matchPrograms(programs,profile){return programs.map(p=>evaluate(p,profile)).sort((a,b)=>{const rank={confirmed:4,probable:3,to_verify:2,not_eligible:1};return rank[b.eligibility]-rank[a.eligibility]||b.relevance-a.relevance;});}