import assert from 'node:assert/strict';
import {matchPrograms,availabilityOf,evaluate} from '../engine.mjs';
import {loadCatalog} from '../scripts/catalog-loader.mjs';
const programs=await loadCatalog();
const find=(results,id)=>results.find(r=>r.program.id===id);
let r=matchPrograms(programs,{canton:'VD',fte:40,description:'développer un prototype de nouveau produit avec bureau ingénierie externe',industry_hightech:true,rd_or_production_in_canton:true,industrial_company:true,production_tool_in_canton:true,is_startup:false,market_established:true,project_started:false,as_of_date:'2026-10-01'});
assert.notEqual(find(r,'vd-spei-product').eligibility,'not_eligible');
assert.equal(find(r,'ge-opi-feasibility').eligibility,'not_eligible');
assert.equal(find(r,'vd-spei-product').availability.code,'upcoming');
r=matchPrograms(programs,{canton:'GE',fte:300,description:'étude innovation avec université',industry_hightech:true,swiss_research_partner:true,as_of_date:'2026-10-01'});
assert.equal(find(r,'ch-innosuisse-cheque').eligibility,'not_eligible');
r=matchPrograms(programs,{canton:'VD',fte:50,description:'participer à un salon international avec un stand',industry_hightech:true,rd_or_production_in_canton:true,project_started:false,as_of_date:'2026-10-05'});
assert.ok(find(r,'vd-spei-exhibition').relevance>=70);
assert.equal(find(r,'vd-spei-exhibition').availability.code,'open');
r=matchPrograms(programs,{canton:'GE',fte:20,description:'étude de faisabilité proof of concept avec HES-SO Genève',is_startup:true,geneva_research_partner:true,as_of_date:'2026-10-01'});
assert.ok(find(r,'ge-opi-feasibility').relevance>=65);
assert.equal(find(r,'ge-opi-feasibility').eligibility,'probable');
assert.equal(find(r,'ge-opi-feasibility').availability.code,'call_based');
r=matchPrograms(programs,{canton:'GE',fte:30,description:'tester un marché en Asie avec partenaire local indépendant',is_startup:true,foreign_local_partner:true,as_of_date:'2026-10-01'});
assert.ok(find(r,'ch-innowwide-2026').relevance>=50);
r=matchPrograms(programs,{canton:'VD',fte:30,description:'nouveau produit industriel',industry_hightech:true,rd_or_production_in_canton:true,project_started:true,as_of_date:'2026-10-01'});
assert.equal(find(r,'vd-spei-product').eligibility,'not_eligible');
r=matchPrograms(programs,{canton:'GE',fte:20,description:'installation pilote innovante avant industrialisation',industrial_company:true,project_started:false,as_of_date:'2026-10-01'});
assert.ok(find(r,'ge-opi-fip').relevance>=50);
assert.notEqual(find(r,'ge-opi-fip').eligibility,'confirmed');
r=matchPrograms(programs,{canton:'VD',fte:80,description:'réduire la consommation électrique des moteurs et de l’air comprimé',project_started:false,as_of_date:'2026-10-01'});
assert.ok(find(r,'ch-prokilowatt-project').relevance>=50);
assert.equal(find(r,'ch-eurostars-2026').availability.code,'closed');
assert.deepEqual(availabilityOf({status:'open_from_2026-10-05'},'2026-10-01').code,'upcoming');
assert.deepEqual(availabilityOf({status:'open_from_2026-10-05'},'2026-10-05').code,'open');
const manual=evaluate({id:'manual',name:'Manual',authority:'Test',cantons:['ALL'],project_types:['innovation'],keywords:['innovation'],funding:{},hard_requirements:[],documents:[],status:'open',manual_checks:['Vérifier un critère humain.']},{canton:'VD',fte:3,description:'innovation',as_of_date:'2026-10-01'});
assert.equal(manual.eligibility,'probable');
console.log(`SubvenCH engine tests: OK (${programs.length} programmes)`);
