import fs from 'node:fs';
import assert from 'node:assert/strict';
import {matchPrograms} from '../engine.mjs';
const programs=JSON.parse(fs.readFileSync(new URL('../data/programs.json',import.meta.url),'utf8'));
const find=(results,id)=>results.find(r=>r.program.id===id);
let r=matchPrograms(programs,{canton:'VD',fte:40,description:'développer un prototype de nouveau produit avec bureau ingénierie externe',industry_hightech:true,rd_or_production_in_canton:true,industrial_company:true,production_tool_in_canton:true,is_startup:false,market_established:true,project_started:false});
assert.notEqual(find(r,'vd-spei-product').eligibility,'not_eligible');
assert.equal(find(r,'ge-opi-feasibility').eligibility,'not_eligible');
r=matchPrograms(programs,{canton:'GE',fte:300,description:'étude innovation avec université',industry_hightech:true,swiss_research_partner:true});
assert.equal(find(r,'ch-innosuisse-cheque').eligibility,'not_eligible');
r=matchPrograms(programs,{canton:'VD',fte:50,description:'participer à un salon international avec un stand',industry_hightech:true,rd_or_production_in_canton:true,project_started:false});
assert.ok(find(r,'vd-spei-exhibition').relevance>=70);
r=matchPrograms(programs,{canton:'GE',fte:20,description:'étude de faisabilité proof of concept avec HES-SO Genève',is_startup:true,geneva_research_partner:true});
assert.ok(find(r,'ge-opi-feasibility').relevance>=65);
assert.equal(find(r,'ge-opi-feasibility').eligibility,'confirmed');
r=matchPrograms(programs,{canton:'GE',fte:30,description:'tester un marché en Asie avec partenaire local indépendant',is_startup:true,foreign_local_partner:true});
assert.ok(find(r,'ch-innowwide-2026').relevance>=50);
r=matchPrograms(programs,{canton:'VD',fte:30,description:'nouveau produit industriel',industry_hightech:true,rd_or_production_in_canton:true,project_started:true});
assert.equal(find(r,'vd-spei-product').eligibility,'not_eligible');
console.log('SubvenCH engine tests: OK');