from pathlib import Path
p=Path('dont100-apk/app/src/main/assets/index.html')
s=p.read_text(encoding='utf-8')

s=s.replace('window.D100V4={runSeed:4,runId:"apk-polish"','window.D100V4={runSeed:(()=>{try{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]}catch{return Date.now()}})(),runId:"apk-final"')
s=s.replace('const BUILD="4.2.0-rc.1.2-polish"','const BUILD="4.2.0-final"')
s=s.replace('level:Math.min(100,Math.max(1,Number(localStorage.getItem(STORAGE.level)||18)))','level:Math.min(100,Math.max(1,Number(localStorage.getItem(STORAGE.level)||1)))')
s=s.replace('best:Math.min(100,Math.max(1,Number(localStorage.getItem(STORAGE.best)||18)))','best:Math.min(100,Math.max(1,Number(localStorage.getItem(STORAGE.best)||1)))')
s=s.replace('v4.2-rc.1.2</span>','v4.2 FINAL</span>')

old='''function arcadeCanvas(label){
 const wrap=document.createElement("div");wrap.className="arcade-wrap";const c=document.createElement("canvas");c.className="arcade-canvas";c.width=360;c.height=220;c.setAttribute("aria-label",label);wrap.appendChild(c);els.playArea.appendChild(wrap);return c;
}'''
new='''function arcadeCanvas(label){
 const wrap=document.createElement("div");wrap.className="arcade-wrap";const c=document.createElement("canvas");c.className="arcade-canvas";const dpr=Math.min(3,Math.max(1,window.devicePixelRatio||1));c.width=Math.round(360*dpr);c.height=Math.round(220*dpr);c.dataset.logicalW="360";c.dataset.logicalH="220";c.setAttribute("aria-label",label);wrap.appendChild(c);els.playArea.appendChild(wrap);const ctx=c.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";return c;
}
function arcadeControlDeck(kind="slide",label="CONTROL"){
 const deck=document.createElement("div");deck.className=`arcade-control-deck ${kind}`;const pad=document.createElement("div");pad.className="arcade-trackpad";pad.setAttribute("role","slider");pad.setAttribute("aria-label",label);pad.innerHTML='<span class="control-arrow">‹</span><b class="control-thumb">↔</b><span class="control-arrow">›</span>';deck.appendChild(pad);let button=null;if(kind==="move-fire"){button=document.createElement("button");button.className="arcade-fire-btn";button.type="button";button.textContent="●";button.setAttribute("aria-label",tr("DISPARAR","FIRE","TIRER"));deck.appendChild(button)}els.playArea.appendChild(deck);return{deck,pad,button};
}
function bindRelativePad(pad,onMove){
 let active=false,lastX=0;const thumb=pad.querySelector(".control-thumb");const down=e=>{active=true;lastX=e.clientX;pad.classList.add("active");try{pad.setPointerCapture(e.pointerId)}catch{}};const move=e=>{if(!active)return;const r=pad.getBoundingClientRect(),dx=e.clientX-lastX;lastX=e.clientX;onMove(dx*360/Math.max(1,r.width));const pct=Math.max(-42,Math.min(42,(e.clientX-r.left)/r.width*84-42));if(thumb)thumb.style.transform=`translateX(${pct}px)`};const up=()=>{active=false;pad.classList.remove("active");if(thumb)thumb.style.transform="translateX(0)"};pad.addEventListener("pointerdown",down);pad.addEventListener("pointermove",move);pad.addEventListener("pointerup",up);pad.addEventListener("pointercancel",up);
}
function drawArcadeBackdrop(ctx,kind,ts=0){
 ctx.save();const g=ctx.createLinearGradient(0,0,0,220);if(kind==="space"){g.addColorStop(0,"#07122f");g.addColorStop(1,"#172c67")}else if(kind==="terrace"){g.addColorStop(0,"#78d7ff");g.addColorStop(.58,"#d9f2ff");g.addColorStop(1,"#f8d797")}else if(kind==="road"){g.addColorStop(0,"#97d9ff");g.addColorStop(.55,"#d8eeff");g.addColorStop(1,"#595b6f")}else{g.addColorStop(0,"#0b1641");g.addColorStop(1,"#28195d")}ctx.fillStyle=g;ctx.fillRect(0,0,360,220);if(kind==="space"||kind==="night"){for(let i=0;i<34;i++){const x=(i*83+17)%360,y=(i*47+11)%200;ctx.globalAlpha=.35+((i%4)*.15);ctx.fillStyle=i%7===0?"#ffd85c":"#fff";ctx.beginPath();ctx.arc(x,y,(i%5===0?1.7:1),0,7);ctx.fill()}ctx.globalAlpha=1}if(kind==="space"){ctx.globalAlpha=.28;ctx.fillStyle="#7d62ff";ctx.beginPath();ctx.arc(35,190,60,Math.PI,0);ctx.fill();ctx.fillStyle="#3ac8ff";ctx.beginPath();ctx.arc(330,215,74,Math.PI,0);ctx.fill();ctx.globalAlpha=1}if(kind==="terrace"){ctx.globalAlpha=.5;ctx.fillStyle="#7fc768";ctx.beginPath();ctx.moveTo(0,150);ctx.lineTo(70,95);ctx.lineTo(130,145);ctx.lineTo(220,80);ctx.lineTo(360,148);ctx.lineTo(360,220);ctx.lineTo(0,220);ctx.fill();ctx.globalAlpha=.75;ctx.fillStyle="#67c7e8";ctx.fillRect(0,158,360,62);ctx.globalAlpha=1;ctx.fillStyle="#f4ead9";ctx.fillRect(0,190,360,30)}if(kind==="road"){ctx.fillStyle="#555968";ctx.beginPath();ctx.moveTo(115,220);ctx.lineTo(158,70);ctx.lineTo(202,70);ctx.lineTo(245,220);ctx.fill()}ctx.restore();
}'''
assert old in s
s=s.replace(old,new)
s=s.replace('function canvasPointerX(e,c){const r=c.getBoundingClientRect();return Math.max(0,Math.min(c.width,(e.clientX-r.left)*c.width/r.width))}','function canvasPointerX(e,c){const r=c.getBoundingClientRect();return Math.max(0,Math.min(360,(e.clientX-r.left)*360/r.width))}')
s=s.replace('function canvasPointerY(e,c){const r=c.getBoundingClientRect();return Math.max(0,Math.min(c.height,(e.clientY-r.top)*c.height/r.height))}','function canvasPointerY(e,c){const r=c.getBoundingClientRect();return Math.max(0,Math.min(220,(e.clientY-r.top)*220/r.height))}')
s=s.replace('const swing=Math.sin(t*.006)*9;','const swing=Math.sin(t*.0055)*8;')

repls=[
(''' const c=arcadeCanvas("Star Blaster"),ctx=c.getContext("2d"),player={x:180},bullets=[],enemies=[];let hits=0,last=performance.now(),spawn=0;
 const makeEnemy=()=>enemies.push({x:rint(r,28,332),y:-10,v:34+hard*3+rint(r,0,22),w:18});for(let i=0;i<5;i++){makeEnemy();enemies[i].y=22+i*28}
 let drag=false;c.addEventListener("pointerdown",e=>{drag=true;player.x=canvasPointerX(e,c);bullets.push({x:player.x,y:186,v:210});tone(520,.03,"square",.018);try{c.setPointerCapture(e.pointerId)}catch{}});c.addEventListener("pointermove",e=>{if(drag)player.x=canvasPointerX(e,c)});c.addEventListener("pointerup",()=>drag=false);c.addEventListener("pointercancel",()=>drag=false);''',
''' const c=arcadeCanvas("Star Blaster"),ctx=c.getContext("2d"),player={x:180},bullets=[],enemies=[];let hits=0,last=performance.now(),spawn=0;
 const ctl=arcadeControlDeck("move-fire",tr("MOVER","MOVE","BOUGER"));bindRelativePad(ctl.pad,dx=>player.x=Math.max(16,Math.min(344,player.x+dx*1.35)));const fire=()=>{bullets.push({x:player.x,y:186,v:210});tone(520,.03,"square",.018)};ctl.button.addEventListener("pointerdown",fire);
 const makeEnemy=()=>enemies.push({x:rint(r,28,332),y:-10,v:34+hard*3+rint(r,0,22),w:18});for(let i=0;i<5;i++){makeEnemy();enemies[i].y=22+i*28}'''),
(''' const c=arcadeCanvas("Paddle Rescue"),ctx=c.getContext("2d"),p={x:150,w:68},b={x:180,y:80,vx:95,vy:120};let last=performance.now(),bounces=0;
 const move=e=>p.x=Math.max(0,Math.min(360-p.w,canvasPointerX(e,c)-p.w/2));c.addEventListener("pointerdown",move);c.addEventListener("pointermove",move);''',
''' const c=arcadeCanvas("Paddle Rescue"),ctx=c.getContext("2d"),p={x:150,w:68},b={x:180,y:80,vx:95,vy:120};let last=performance.now(),bounces=0;
 const ctl=arcadeControlDeck("slide",tr("DESLIZA PARA MOVER LA BARRA","SLIDE TO MOVE THE PADDLE","GLISSE POUR BOUGER LA BARRE"));bindRelativePad(ctl.pad,dx=>p.x=Math.max(0,Math.min(360-p.w,p.x+dx*1.45)));'''),
(''' const c=arcadeCanvas("Waiter Balance"),ctx=c.getContext("2d");let target=0,tilt=0,glass=0,vel=0,last=performance.now(),safe=0;
 const move=e=>{target=(canvasPointerX(e,c)/360-.5)*.30};c.addEventListener("pointerdown",move);c.addEventListener("pointermove",move);''',
''' const c=arcadeCanvas("Waiter Balance"),ctx=c.getContext("2d");let target=0,tilt=0,glass=0,vel=0,last=performance.now(),safe=0;
 const ctl=arcadeControlDeck("slide",tr("DESLIZA PARA EQUILIBRAR","SLIDE TO BALANCE","GLISSE POUR ÉQUILIBRER"));bindRelativePad(ctl.pad,dx=>target=Math.max(-.30,Math.min(.30,target+dx/520)));'''),
(''' const c=arcadeCanvas("Catch Stars"),ctx=c.getContext("2d");let x=180,last=performance.now(),spawn=0,got=0,items=[];const move=e=>x=canvasPointerX(e,c);c.addEventListener("pointerdown",move);c.addEventListener("pointermove",move);''',
''' const c=arcadeCanvas("Catch Stars"),ctx=c.getContext("2d");let x=180,last=performance.now(),spawn=0,got=0,items=[];const ctl=arcadeControlDeck("slide",tr("DESLIZA PARA MOVER LA CESTA","SLIDE TO MOVE THE BASKET","GLISSE POUR BOUGER LE PANIER"));bindRelativePad(ctl.pad,dx=>x=Math.max(34,Math.min(326,x+dx*1.45)));'''),
(''' const c=arcadeCanvas("Breakout"),ctx=c.getContext("2d"),p={x:145,w:70},b={x:180,y:150,vx:105,vy:-125,r:6},br=[];let last=performance.now(),hits=0;for(let row=0;row<2;row++)for(let col=0;col<5;col++)br.push({x:25+col*66,y:28+row*26,w:52,h:14,dead:false});
 const move=e=>p.x=Math.max(0,Math.min(360-p.w,canvasPointerX(e,c)-p.w/2));c.addEventListener("pointerdown",move);c.addEventListener("pointermove",move);''',
''' const c=arcadeCanvas("Breakout"),ctx=c.getContext("2d"),p={x:145,w:70},b={x:180,y:150,vx:105,vy:-125,r:6},br=[];let last=performance.now(),hits=0;for(let row=0;row<2;row++)for(let col=0;col<5;col++)br.push({x:25+col*66,y:28+row*26,w:52,h:14,dead:false});
 const ctl=arcadeControlDeck("slide",tr("DESLIZA PARA MOVER LA BARRA","SLIDE TO MOVE THE PADDLE","GLISSE POUR BOUGER LA BARRE"));bindRelativePad(ctl.pad,dx=>p.x=Math.max(0,Math.min(360-p.w,p.x+dx*1.45)));''')]
for a,b in repls:
    assert a in s
    s=s.replace(a,b)

s=s.replace('ctx.clearRect(0,0,360,220);ctx.fillStyle="#111";for(let i=0;i<26;i++){const x=(i*67+n*13)%360,y=(i*41+Math.floor(ts/35))%220;ctx.fillRect(x,y,1.5,1.5)}ctx.strokeStyle="#111";ctx.lineWidth=2.2;','ctx.clearRect(0,0,360,220);drawArcadeBackdrop(ctx,"space",ts);ctx.fillStyle="#fff";ctx.strokeStyle="#f7f8ff";ctx.lineWidth=2.2;')
s=s.replace('ctx.clearRect(0,0,360,220);ctx.save();ctx.translate(180,158);ctx.rotate(tilt);ctx.strokeStyle="#111";','ctx.clearRect(0,0,360,220);drawArcadeBackdrop(ctx,"terrace",ts);ctx.save();ctx.translate(180,158);ctx.rotate(tilt);ctx.strokeStyle="#2c2118";')
s=s.replace('ctx.clearRect(0,0,360,220);ctx.strokeStyle="#aaa";ctx.setLineDash([8,8]);','ctx.clearRect(0,0,360,220);drawArcadeBackdrop(ctx,"road",ts);ctx.strokeStyle="rgba(255,255,255,.7)";ctx.setLineDash([8,8]);')

css=r'''
/* v4.2 FINAL — approved art direction + finger-safe controls */
html,body{height:100%;max-height:100dvh;overflow:hidden}body{min-height:100dvh;overscroll-behavior:none;background:radial-gradient(circle at 12% 4%,rgba(95,69,255,.12),transparent 26%),radial-gradient(circle at 88% 12%,rgba(50,183,255,.12),transparent 25%),linear-gradient(180deg,#f9faff,#f7f4ee)}.shell{height:100dvh;min-height:0;max-height:100dvh;overflow:hidden;padding:max(9px,env(safe-area-inset-top)) 11px max(8px,env(safe-area-inset-bottom));gap:7px}.logo b{background:linear-gradient(145deg,#8059ff,#5a36f2 65%,#3d24c9);box-shadow:0 5px 0 #2d1b94,0 10px 22px rgba(86,62,240,.24)}.game-card{min-height:0!important;flex:1;padding:12px 13px 10px}.challenge{margin:8px 0 3px}.challenge h1{font-size:clamp(25px,7.3vw,34px);line-height:1.01}.challenge p{font-size:clamp(13px,3.7vw,16px);font-weight:760;color:#55566e}.play-area{min-height:0;flex:1;margin:4px -2px 0;padding:5px 0}.mascot-zone{min-height:118px}.stickman{max-height:140px}
body.arcade-level .game-card{min-height:0!important}body.arcade-level .play-area{min-height:0;display:flex;flex-direction:column;justify-content:center;gap:8px;padding:3px 0 0;margin-top:2px;background:transparent;border:0}body.arcade-level .mascot-zone{display:none}.arcade-wrap{width:min(100%,430px);height:auto!important;aspect-ratio:360/220;border:2px solid rgba(14,18,48,.92);border-radius:24px;overflow:hidden;background:#101738;box-shadow:0 11px 0 rgba(31,34,78,.10),0 18px 34px rgba(34,44,110,.17);touch-action:none}.arcade-canvas{display:block;width:100%;height:100%!important;background:transparent;touch-action:none}.arcade-control-deck{width:min(100%,430px);min-height:76px;border:2px solid rgba(29,31,75,.25);border-radius:23px;padding:9px;background:linear-gradient(180deg,#fff,#f5f7ff);box-shadow:0 7px 18px rgba(28,34,88,.10);display:grid;grid-template-columns:1fr;gap:8px;align-items:center;touch-action:none;user-select:none}.arcade-control-deck.move-fire{grid-template-columns:minmax(0,1fr) 78px}.arcade-trackpad{position:relative;height:56px;border-radius:999px;border:1.5px solid rgba(62,66,140,.18);background:linear-gradient(90deg,rgba(204,105,255,.25),rgba(91,70,255,.18) 50%,rgba(43,189,255,.27));display:flex;align-items:center;justify-content:space-between;padding:0 17px;touch-action:none;overflow:hidden}.arcade-trackpad::before{content:"DESLIZA AQUÍ";position:absolute;left:50%;top:5px;transform:translateX(-50%);font-size:8px;font-weight:1000;letter-spacing:1.1px;color:rgba(43,45,97,.54)}.control-arrow{font-size:28px;font-weight:1000;color:#5e56aa}.control-thumb{display:grid;place-items:center;width:44px;height:44px;border-radius:50%;background:linear-gradient(145deg,#7559ff,#405ee8);color:#fff;border:3px solid #fff;box-shadow:0 5px 0 #30399b;font-size:22px;transition:transform .08s linear}.arcade-fire-btn{height:58px;border:0;border-radius:20px;background:linear-gradient(145deg,#ff4d79,#ff315c 65%,#d70f40);color:#fff;font-size:29px;font-weight:1000;box-shadow:0 6px 0 #9e1839}.stickman.sprite-panic{animation-duration:.34s!important}.stickman.sprite-nervous{animation-duration:.72s!important}.stickman.sprite-dance{animation-duration:1.2s!important}.stickman.sprite-win{animation-duration:.68s!important}footer{flex:none;font-size:8px;padding:0 2px}
@media(max-height:760px){.shell{gap:5px}.topbar{transform:scale(.94);transform-origin:center top;margin-bottom:-4px}.game-card{padding:9px 11px 8px}.challenge h1{font-size:clamp(23px,6.8vw,30px)}.challenge p{font-size:13px}.mascot-zone{min-height:92px}.stickman{height:110px}.arcade-wrap{max-height:28dvh;width:auto;max-width:100%;align-self:center}.arcade-control-deck{min-height:64px;padding:6px}.arcade-trackpad{height:48px}.control-thumb{width:38px;height:38px}.arcade-fire-btn{height:50px}}
@media(max-height:660px){.challenge h1{font-size:22px}.challenge p{font-size:12px}.checkpoint-text{display:none}.arcade-wrap{max-height:25dvh}.arcade-control-deck{min-height:58px}.arcade-trackpad{height:43px}.arcade-trackpad::before{display:none}.control-thumb{width:34px;height:34px;font-size:18px}.arcade-fire-btn{height:45px}footer{display:none}}
'''
s=s.replace('</style>',css+'\n</style>',1)
p.write_text(s,encoding='utf-8')
assert '4.2.0-final' in s and 'arcade-control-deck' in s
print('FINAL patch applied',p.stat().st_size)
